apiVersion: v1
kind: Service
metadata:
  name: k8-manager-service
spec:
  selector:
    app: k8-manager-server
  ports:
    - protocol: TCP
      port: 5100
      targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-manager-server
  labels:
    app: k8-manager-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-manager-server
  template:
    metadata:
      labels:
        app: k8-manager-server
    spec:
      containers:
        - name: k8-manager-server
          image: istiyaqmi9/k8-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80